### PR TITLE
Save damage to db (optional)

### PR DESCRIPTION
**Pull request by Liam0**
Reverting some stuff while adding vehicle damage save its more clean, promise i
wont touch them again unless you dare to report a bug xD

### CODE REVIEW

**Comment by Jawshy** [comment]
I would like to see what happens when a player garages a vehicle that is about to explode... and then retrieves it.

**Comment by Liam0** [comment]
Nothing happens it just spawns in equally wrecked and ur still gonna have to repair it.

**Comment by silvercn** [comment]
Was going to write this too, but now ill test this and will report back.

**Comment by Liam0** [comment]
thx @Silvercn. i didn't get it to do anything weirdly even with 90% of the vehicle broken. besides its not like ur just gonna drive it to the garage when its that broken. its simply to avoid people using the garage as a free repair. Remember the mission file changes too

**Comment by silvercn** [comment]
Okay checked files 2 Times, but its not storing, its written in the database but did ont changed something in damage value, also the vehicle is still ingame.

**Comment by Liam0** [comment]
@silvercn checking it now.

**Comment by Liam0** [comment]
works fine. both when its true and false. did you remember https://github.com/ArmaLife/Altis/pull/364

**Comment by silvercn** [comment]
Works fine now, made a copy misstake. :)

**Comment by danielstuart14** [comment]
@Liam0 when it get ready for merge (if it isn't by now), you can do it.

**Pull request closed without merging**
